update: fixes

diff --git a/4/Dockerfile b/4/Dockerfile
--- a/4/Dockerfile
+++ b/4/Dockerfile
@@ -20,13 +20,17 @@ USER root
 
 # Install wp-cli, http://wp-cli.org
 #ENV WP_CLI_CONFIG_PATH /var/www/html/wp-cli.yml
-RUN set -ex \
-    && curl --retry 7 --fail -Ls -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
-    && chmod +x wp-cli.phar \
-    && mv wp-cli.phar /usr/local/bin/wp \
-    && wp --info --allow-root
+#RUN set -ex \
+#    && curl --retry 7 --fail -Ls -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar \
+#    && chmod +x wp-cli.phar \
+#    && mv wp-cli.phar /usr/local/bin/wp \
+#    && wp --info --allow-root
 
 RUN set -ex; \
+    curl --retry 7 --fail -Ls -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar; \
+    chmod +x wp-cli.phar; \
+    mv wp-cli.phar /usr/local/bin/wp; \
+    wp --info --allow-root; \
     mv /usr/local/bin/actions.mk /usr/local/bin/wordpress-php.mk; \
     mkdir -p /usr/src/wordpress/; \
 	    chown -R anaxexp:anaxexp /usr/src/wordpress/; \
